# Generated by Django 5.1.2 on 2024-11-05 03:35

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(default='null')),
                ('model', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=myapp.models.unique_image_name)),
                ('price', models.CharField(default='free', max_length=50)),
                ('car_type', models.CharField(default='null', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
