# Generated by Django 5.1.2 on 2024-11-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='seller_phone',
            field=models.CharField(default='+2547...', max_length=15),
        ),
    ]
